### ISSUE TITLE
predict! doesn't modify anything

### ISSUE THREAD

**Issue by cstjean** [mschauer/Kalman.jl#1]
By Julia's `!` convention, I expected `predict!` to modify... something, but it doesn't seem to. Shall I make a PR to take out the `!`?

```julia
function predict!(s, x, P, t, M::LinearHomogSystem)
    x = evolve(s, x, P, t, M)
    Ppred = M.Phi*P*M.Phi' + M.Q
    x, Ppred, M.Phi
end
```

**Comment by mschauer** [comment]
`!` indicates in this context that the overloads of this function *may*  modify arguments. This happens naturally, if you mix `StaticArray`s and ordinary `Array`s. This is similar to the function `_chol!` from Base, which modifies arrays, but of course does not modify numbers and static arrays.

**Comment by cstjean** [comment]
Which argument would `predict!` modify? `x`?

**Comment by mschauer** [comment]
Yes, that is what I had in mind I believe.

**Comment by cstjean** [comment]
Then shouldn't `evolve` be turned into `evolve!(s, x, P, t, M)`, with separate methods for mutable and immutable arrays?

**Comment by mschauer** [comment]
Ah, that may well be. Maybe the best way to figure this out to give a shot at a performant, modifiying `Array` version of the filter and see what is needed.

**Comment by mschauer** [comment]
Oudated
