### ISSUE TITLE
predict and evolve ignore temporal information

### ISSUE THREAD

**Issue by yakir12** [mschauer/Kalman.jl#7]
Hi Moritz!
I'm not sure, but I think `evolve` and therefore `predict!` ignore the temporal arguments `s` and `t`. So if we have a system where the speed `x` is in km per hour but the states are measured once per minute then the estimated progress is exaggerated by 60.

**Comment by mschauer** [comment]
Filters with inhomogeneous times steps are on a todo list. Currently it is assumed that `predict` is called with time steps such that `x(t+delta) = Phi x(t) + ...` is correct (`Phi` has to be chosen such that this holds).

**Comment by yakir12** [comment]
Well, the time steps are homogeneous in the sense that the temporal distance between each observation is equal. This is obviously related to allowing for a `Unitful` functionality, but I assume it's true in general: if the model predicts that the object will advance 1 km per hour and the observations are taken on a homogeneous albeit different time scale of once per minute, is it still defined as a `LinearHomogSystem`?

**Comment by mschauer** [comment]
It can be expressed as a LinearHomog system with I believe `Phi2 = expm(1min/1km*logm(Phi))`

**Comment by yakir12** [comment]
Weird, I mean, wouldn't it work if I just admitted defeat and used the speed of the object but in km per minute instead?

**Comment by mschauer** [comment]
E.g. if you have two update steps in a time frame with `Phi2` and `b2` instead of one update with `Phi` and `b`, then you want
```
Phi2*(Phi2*x + b2) + b2 == Phi*x + b
```
for the predictions to be equal at the end of the time frame

**Comment by yakir12** [comment]
I see.
