### ISSUE TITLE
Why not `__precompile__()`?

### ISSUE THREAD

**Issue by yakir12** [mschauer/Kalman.jl#9]
It would speed the startup...

**Comment by mschauer** [comment]
That should also go to `GaussianDistributions` then?

**Comment by yakir12** [comment]
Yes, those are the rules. The only disadvantage of this step is that if you modify the code a lot and push tons of updates, then you'll have a lot of precompilations. But if the code is more or less good to go, then adding `__precompile__()` speeds things up.

**Comment by mschauer** [comment]
Outdated.

**Comment by yakir12** [comment]
True.
